POST http://localhost:3333/users
content-type: application/json

{
    "name": "livia",
    "email": "testecarla@teste.com",
    "password": "12345678",
    "confirm_password": "12345678"
}

###

GET http://localhost:3333/users

###

GET http://localhost:3333/users/1

###

PUT http://localhost:3333/users/1
content-type: application/json

{
    "name": "larissa",
    "email": "testelarissa@teste.com",
    "password": "12345678",
    "confirm_password": "12345678"
}

###

DELETE http://localhost:3333/users/2

###

POST http://localhost:3333/thoughts
content-type: application/json

{
    "title": "Pensamento 02",
    "description": "Pensamento do dia"
}

###
POST http://localhost:3333/thoughts
content-type: application/json

{
    "title": "Pensamento 06",
    "description": "atualizado"
}
###
GET http://localhost:3333/thoughts

###

GET http://localhost:3333/thoughts/2

###
PUT http://localhost:3333/users/1
content-type: application/json

{
    "name": "larissa",
    "email": "testelarissa@teste.com",
    "password": "12345678",
    "confirm_password": "12345678"
}
